### ISSUE TITLE
Channel is not displayed

### ISSUE THREAD

**Issue by ghost** [Twoure/KissNetwork.bundle#1]
Hello, I installed this channel in the Plug-ins folder (followed all instructions) but channel is not displayed in the Channels section. I am testing on Plex Media Server Version 0.9.12.11 / Web Version 2.4.18

**Comment by ghost** [comment]
also the instruction on the readme file is for a channel called "Kiss Manga"
the download link on readme file is : http://github.com/Twoure/KissManga.bundle/zipball/master

correct download link : https://github.com/Twoure/KissNetwork.bundle/archive/master.zip

**Comment by Twoure** [comment]
Thanks, just updated the readme to the correct download link.  Now with the link I provided it should do a redirect to https://codeload.github.com/Twoure/KissManga.bundle/legacy.zip/master for downloading

Did the channel show up after you tried the correct download?

**Comment by ghost** [comment]
yes, I tried the new download link but the channel is still not shown on "Channels" section.

**Comment by Twoure** [comment]
What platform are your running Plex Media Server on? If it's a Linux based one, could be a permissions error.  Also the channel's hierarchy (directory tree) should be
- Plug-Ins
  - KissNetwork.bundle
    - Contents
      - Code
      - etc...

so could be that when you extract the zip file, you're getting an extra folder at the head of the tree.

Also tested the channel today on a separate PMS on Ubuntu, and it worked fine.  So like I said could be a platform issue or perhaps one the scenarios above.

**Comment by ghost** [comment]
I am running Plex on Windows 10 (Plex Media Server Version 0.9.12.11 / Web Version 2.4.18)
I tried re-downloading, restarting plex several times, cleared cache, restart the computer, and none of them worked. 
When I go to channels, all my channels are there except this one. The folder exist in the plugin-ins folder and I installed it same as other times when installing plex plugins

**Comment by Twoure** [comment]
Ok, found out it was a JavaScript engine error in my cfscrape code.  Modified it and tested the channel on PMS on a Windows 10 machine.  Everything seems to work now. Let me know if it works for you.

Also for future reference and debugging watch the log files with PowerShell to see if an error occurs, PowerShell should already be included with Windows 10.
Run this in PowerShell to watch the file as it grows,

```
Get-Content "C:\Users\username\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.plugins.kissnetwork.log" -Wait
```

replace **_username**_ with your own.  To stop watching log file press `Ctrl+c`.

**Comment by ghost** [comment]
@Twoure great, it works now. 
also is it possible to display channel art for each show?

**Comment by Twoure** [comment]
No not yet, I address that [here](https://github.com/Twoure/KissNetwork.bundle#known-issues).  For now if you choose to cache the images locally, they will show up in your bookmark list.

Also I just updated the channel to now include an option to select which sites to view content from.  Now you can select only the cartoon site to view or any combo of the sites.

Going to close this issue now since it's displaying for you.  Start another issue if you have more thoughts or issues.  Thanks
