### ISSUE TITLE
Blank?

### ISSUE THREAD

**Issue by bennetthermanoff** [Twoure/KissNetwork.bundle#11]
Whenever I go into a category it just come back blank, I have restarted my server entirely but still no luck

**Comment by Twoure** [comment]
Which site(s), i.e. Cartoon, Anime, Drama, etc...

Also please include log files.  Log info I need can be found [here](https://forums.plex.tv/discussion/186988/rel-kissnetwork/p6#Comment_1084965).

**Comment by bennetthermanoff** [comment]
[here's my logs, i have anime and cartoon turned on.](https://drive.google.com/a/ga.usmk12.org/file/d/0B5LZSUbVqjsHWmlQWndad3JVMEk/view?usp=drivesdk)

**Comment by Twoure** [comment]
Does this file exist,

```
C:\Users\Bennett\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.plugins.kissnetwork\Header_Dict
```

and does it have headers for all 5 sections within it?  If the file exist but not all the headers are within, then this is the issue.

**Comment by bennetthermanoff** [comment]
The file does not exist http://i.imgur.com/MjQ5T28.png

**Comment by Twoure** [comment]
Try resetting the `Header_Dict` from within the channels developer tools.

You will need to [Enable Developer Tools](https://github.com/Twoure/KissNetwork.bundle#enable-developer-tools) from the channels preferences.  Then navigate to [**About / Help**](https://github.com/Twoure/KissNetwork.bundle#about--help) --> **Developer Tools** --> [**Header Tools**](https://github.com/Twoure/KissNetwork.bundle#header-tools) and select _Reset Header_Dict File_.

Exit the channel and wait for about 30 seconds before using the channel again (general issues [pt 2](https://github.com/Twoure/KissNetwork.bundle#general)).  Then navigate the channel again and see if the error persist.  If so then please include the new logs.

**Comment by Twoure** [comment]
Forgot to mention, after updating the `Header_Dict` check and make sure the file exist before using the channel.  If it still does not exist, or does but is missing some of the 5 sections, then there could be a different issue.  Regardless please include the new logs, so I can work at tracking down the error.

**Comment by Twoure** [comment]
@xpsKING does [v1.2.1](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.1) fix your issue?

**Comment by bennetthermanoff** [comment]
no, same issue still...

**Comment by bennetthermanoff** [comment]
also forgot to mention I did reset header_dict

**Comment by Twoure** [comment]
Hmm, sorry to hear.  Please include new logs so I can get a better idea of what is going on.  Thanks.

**Comment by bennetthermanoff** [comment]
here you go

**Comment by Twoure** [comment]
Sorry, but you did not include the logs.  Please try again.

**Comment by Twoure** [comment]
[v1.2.2](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.2) now available.  Please try the new version.

**Comment by next2non** [comment]
Hi

Having the same issue even with the new update v1.2.2. It just give "list empty" in all the categories i.e. Cartoon, Anime, etc. I'm running my plex on my synology and using apple tv and iphone to stream. I even tried using the plex web but the same happens, nothing is there!

**Comment by Twoure** [comment]
@next2non 

Please upload logs.  I'll try and see what's happening.  Please refer to [Comment_1084965](https://forums.plex.tv/discussion/186988/rel-kissnetwork/p6#Comment_1084965) for log info.  You can upload the log files as an attachment or a remote link.  Please do not copy/paste logs into a comment.

**Comment by next2non** [comment]
Here are the log files 
[kissnetwork.zip](https://github.com/Twoure/KissNetwork.bundle/files/327228/kissnetwork.zip)

**Comment by Twoure** [comment]
@next2non 

From your logs:

> - set_header cfscrape.get_cookie_string Error: Could not find a JavaScript runtime.

You need a JavaScript runtime globally available for this channel to work.  I suggest Node.js.  
- https://www.synology.com/en-us/dsm/app_packages/Node_js
- https://nodejs.org/en/download/

**Comment by next2non** [comment]
Thanks that nailed it :)

**Comment by Twoure** [comment]
@xpsKING please download and try [v1.2.6](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.6) and let me know if it fixes your issue.

**Comment by bennetthermanoff** [comment]
1.2.6 fixed the issue!

**Comment by kcheema** [comment]
Hi,
I'm having the same issue on my side. Any page that I try to navigate to, it just says that the list is empty.
Here are the logs:

[Kissnetwork Logs.zip](https://github.com/Twoure/KissNetwork.bundle/files/906538/Kissnetwork.Logs.zip)

Can you please take a look?
