### ISSUE TITLE
Plex server exit/crash after episode played

### ISSUE THREAD

**Issue by swotai** [Twoure/KissNetwork.bundle#12]
Plex Server 0.9.16.6, OpenPHT1.5.2, when using the channel to watch an episode of anime, after the anime episode is played the Plex server seems to have crashed.

**Comment by Twoure** [comment]
Seems the channel does not play nicely with PHT or OpenPHT.  I'll take some time to look into this, others in the [forums](https://forums.plex.tv/discussion/186988/rel-kissnetwork#latest) have had similar issues recently.

**Comment by Twoure** [comment]
@swotai have you upgraded your Plex Media Server to `v1.0.0` yet, and if so does it fix any of the issues you were experiencing with this channel on OpenPHT?

**Comment by swotai** [comment]
Just upgraded the PMS to v1, and upgraded OpenPHT embedded to 1.6.2.  It has fixed the channel playback issue!

**Comment by Twoure** [comment]
Thanks @swotai for the feedback.
