### ISSUE TITLE
video unavailable

### ISSUE THREAD

**Issue by jimf54** [Twoure/KissNetwork.bundle#14]
was working great (Thanks by the way)
now getting (Video Unavailable) on all streams on roku client
and
"There was a problem playing this item" on Plex Media Server

**Comment by Twoure** [comment]
Refer to issue #15 for more info.  Fix will be out in the next day or so.

**Comment by Twoure** [comment]
@jimf54 does [v1.2.1](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.1) fix your issue?

**Comment by jimf54** [comment]
V1.2.1 FIXED ISSUE .

Thanks So Much Love This Channel.
