### ISSUE TITLE
KissAsian kissenc v=5

### ISSUE THREAD

**Issue by Prometheusx-git** [Twoure/KissNetwork.bundle#16]
KissAsian has changed their encyrption. Any idea how to handle this?

**Comment by sudovijay** [comment]
it ain't big thing ! they just sending krsk as a post field which actually in the window.krsk ! just check the source code its there

var _0x83d6 = ["\x6B\x72\x73\x6B", "\x3C\x6B\x72\x73\x6B\x3E\x74\x65\x46\x77\x52\x4C\x4A\x6A\x77\x67\x3C\x2F\x6B\x72\x73\x6B\x3E"]'

i.e 
 var _0x83d6 = ["krsk", "<krsk>teFwRLJjwg</krsk>"]

**Comment by Twoure** [comment]
Thanks, will work on this soon.

**Comment by Twoure** [comment]
Fixed, refer to commit: https://github.com/Twoure/KissNetwork.bundle/commit/514094d4de7b4c01789c2e5c965b812f64993f5a

Have yet to merge into master branch, still working on some other bugs.

**Comment by sudovijay** [comment]
you might want to change the content-length value in the headers ! i quess they checking for that ! 
change it to 'Content-Length': '38' !

**Comment by Twoure** [comment]
Thanks for the heads up. Just noticed they changed the post value. Will work out a better fix.

**Comment by sudovijay** [comment]
yep they changed it too "gcGdcrFk" and just count the post field length which will give the content length. they checking for that too . need some better fix for that post though !

**Comment by Twoure** [comment]
Round two!

Fixed in https://github.com/Twoure/KissNetwork.bundle/commit/16f09463db0eb0e05248a3b538182baff533ae9b

Decided to start using `PyExecJS` to evaluate the js obfuscation.  Might make life worse later, but we'll see.

**Comment by Twoure** [comment]
Fixed for now, so closing.
