### ISSUE TITLE
Channel not found

### ISSUE THREAD

**Issue by TheYoke** [Twoure/KissNetwork.bundle#17]
I followed the installation and [faq](https://github.com/Twoure/KissNetwork.bundle/wiki/FAQ---Installation).
I tried to install both manually and via WebTools.bundle.
Still the channel can't be found.
Please help.

[com.plexapp.plugins.kissnetwork.log.txt](https://github.com/Twoure/KissNetwork.bundle/files/310123/com.plexapp.plugins.kissnetwork.log.txt)
[com.plexapp.system.log.txt](https://github.com/Twoure/KissNetwork.bundle/files/310124/com.plexapp.system.log.txt)

**Comment by Twoure** [comment]
Please try the dev branch. [dev zip link download](https://github.com/Twoure/KissNetwork.bundle/archive/dev.zip)

Before installing, Stop your Plex Media Server (PMS).  Then locate and delete the channels prefs file, located here: `Plug-in Support/Preferences/com.plexapp.plugins.kissnetwork.xml`  Then download and install the dev branch, and after start PMS.  If the channel shows up in your PMS, then click on it and wait about 30 seconds before using (info in [general issue pt 1](https://github.com/Twoure/KissNetwork.bundle#general)).  If the channel doesn't work or appear then post logs again.  Regardless, let me know how it goes.

Thanks for checking the wiki.  Wiki is still limited at this time, as I've yet to fill in more information.  Writing documents is not one of my favorite things to do.

**Comment by TheYoke** [comment]
It works. Thanks, man.
I'll let you know if I find any more issue. :+1:
