### ISSUE TITLE
cfscrape needs updating again?

### ISSUE THREAD

**Issue by deeelwy** [Twoure/KissNetwork.bundle#18]
My KissNetwork anime channel stopped working when trying to list videos or doing anything that needs to scrap the web site. I've mostly assumed its because cfscrape itself recently stopped working again after the previous bug about cfscrape breaking was fixed.

[In the bug report on cfscrape's issues page](https://github.com/Anorov/cloudflare-scrape/issues/60) the maintainer wonders if cloud flare changed their js to make cfscrape not work anymore or some other script. So, this might be the new normal: cloud flare breaks script...script needs updating yet again. Maybe make KissNework.bundle try to update cfscrape itself when errors occur. It might be worth the effort if you need to make a new release twice a week from now on. Or this could be the last time it happens.

Attached are the log files other bug posts have mentioned you need to see what's going on.
[com.plexapp.plugins.kissnetwork.log.txt](https://github.com/Twoure/KissNetwork.bundle/files/310628/com.plexapp.plugins.kissnetwork.log.txt)
[com.plexapp.system.log.txt](https://github.com/Twoure/KissNetwork.bundle/files/310629/com.plexapp.system.log.txt)

Also, a peculiarity of my plex configuration is that I'm using [PlexConnect](https://github.com/iBaa/PlexConnect) to support my older 3rd generation Apple TV, which lacks a Plex app or any DLNA support at all. I don't know if this could be a problem, but it used to work just fine.

**Comment by Twoure** [comment]
Thanks for the heads up.  I too noticed it a few days ago, and already alter my `cfscrape` code within the dev branch to compensate.  I've been holding off on the next release because kissasian has been changing there obfuscation about every day for the past week.

Try downloading the dev branch ([dev zip download](https://github.com/Twoure/KissNetwork.bundle/archive/dev.zip)), and let me know how it goes.

**Comment by Twoure** [comment]
I see what was changed within https://github.com/Anorov/cloudflare-scrape/commit/04926684597e6ca61646b5dfb9e252d3dd68ff4b and it works for me as well, so will look into switching my code to be similar.

**Comment by deeelwy** [comment]
Dev branch works great. Browsing stuff and watching videos works now.

Thanks for the clickable zip link.
