### ISSUE TITLE
bookmark functionality is broken

### ISSUE THREAD

**Issue by ghost** [Twoure/KissNetwork.bundle#2]
after updating to recent version, bookmark functionality stopped working and gives "channel not responding error"

**Comment by Twoure** [comment]
Ah sorry, forgot to mention that the bookmarks are stored differently now, so you'll have to delete the Dict file then open KissNetwork channel settings and change something/anything and save.  That should update/create the new Dict.

the dictionary "Dict" will be located in your "Plug-in Support\Data\com.plexapp.plugins.kissnetwork\Dict" for Windows.

**Comment by ghost** [comment]
thank, this resolved the issue.

**Comment by Twoure** [comment]
Thanks for the update.
**Closing Issue.**
