### ISSUE TITLE
Usage issue with Windows/ChromeCast/PS4

### ISSUE THREAD

**Issue by Icehunter** [Twoure/KissNetwork.bundle#20]
I'm having the strangest issue and honestly after reading past issues and the FAQ I couldn't seem to find an answer.

So here's my various devices:
Windows 10 (enterprise)
OSX (latest)
PS4
ChromeCast
Nexus6 w/ Plex Client

The server is running off the Windows 10 machine.

I can:
- Play using Plex client on android ( I can't cast to ChromeCast though)

I can't:
- Play anywhere else either via streaming or anything, no matter which options I choose. But I can browse to my hearts content.

If however I run the server itself off OSX everything works fine; anywhere/anytime.

I've originally thought because my OSX machine is my dev machine and thus has everything under the sun installed for nodejs development that's why it was different.

In the end I made sure my windows machine was up to the same stage of support in terms of development but I'm not able to fix this.

The one error I see however when trying to play is:

```
vendors.d1f37e7….js:252 GET http://192.168.1.115:32400/system/services/url/lookup?url=https%3A%2F%2Fkissanime.to%2FAnime%2FAjin%2FEpisode-001%3Fid%3D121936 404 (Not Found)
```

It seems that url breaks everything on the clients that don't work. If there's anything else I can provide let me know. I'm also knew to use Plex so if extra logging is required let me know (if you would be so kind) as to where that is.

Really loving this channel! So far I'm keeping my laptop open to use it but would prefer to use the desktop instead.

**Comment by Twoure** [comment]
Which Plex Media Server (PMS) version are you running?  The latest Plex Pass `v0.9.17.2` has many transcoder issues, and is causing general issues across the board for many users.

If you are on `v0.9.17.2` and want to stick with it, then make sure your Plex Clients have Direct Play/Stream enabled and ensure this channels [Preferred Video Server](https://github.com/Twoure/KissNetwork.bundle#preferred-video-server) option is set to _KissNetwork_.

> I've originally thought because my OSX machine is my dev machine and thus has everything under the sun installed for nodejs development that's why it was different.
> 
> In the end I made sure my windows machine was up to the same stage of support in terms of development but I'm not able to fix this.

As-far-as Node.js, the channel will run with Window's native JScript but Node.js is more secure.  Thus the strong recommendation to use Node.js.  That said, the javascript runtime is only used when getting site cookies and getting the kissasian video URLs.  Cookies are only reset after they expire.  If you're able to browse the channel, then your javascript runtime setup is working.

> If there's anything else I can provide let me know. I'm also knew to use Plex so if extra logging is required let me know (if you would be so kind) as to where that is.

You do not need Plex server extra logging, but do make sure the KissNetwork channel's [Enable Debug Logging](https://github.com/Twoure/KissNetwork.bundle#enable-debug-logging) is set within the channel's preferences.

Reproduce the error, then upload the required logs as an attachment or a link.  Need `com.plexapp.plugins.kissnetwork.log` and `com.plexapp.system.log`. Log location info can be found [here](https://support.plex.tv/hc/en-us/articles/201106148-Channel-Log-Files).

> I'm having the strangest issue and honestly after reading past issues and the FAQ I couldn't seem to find an answer.

I have a release/support thread over in the Plex forums. You may find some useful info there as well.
https://forums.plex.tv/discussion/186988/rel-kissnetwork#latest

**Comment by Twoure** [comment]
@Icehunter any updates?

**Comment by Icehunter** [comment]
Sorry ><; I'm in the process of moving and got my computer setup again.
I'll try to have something later next week if that's okay when it's all
said and done.

**Comment by Twoure** [comment]
@Icehunter please download and try [v1.2.7](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.7) and let me know if it fixes your issue.

**Comment by Twoure** [comment]
[v1.2.8](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.8) now available.  If you have further issues after updating to `v1.2.8`, then please refer to [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue).
