### ISSUE TITLE
KissManga fails CFTest with 503 error

### ISSUE THREAD

**Issue by nvaldes** [Twoure/KissNetwork.bundle#21]
The log is complaining about a 503 causing KissManga to fail CFTest, and then prompting me to install NodeJS (which is already installed).  Can you please help me figure out what I did wrong.

I also tried installing your dev branch, which is what I'm currently running.  Please let me know if I should go back to master.

Log files are attached.

**Comment by nvaldes** [comment]
[kissnetwork.logs.zip](https://github.com/Twoure/KissNetwork.bundle/files/342884/kissnetwork.logs.zip)

**Comment by Twoure** [comment]
Thanks, I'm also experiencing this issue across all the sites.  Looking into a fix now.

**Comment by Twoure** [comment]
Looks like CloudFlare removed a value from the headers, causing `cfscrape` to mess up.  Patched in https://github.com/Twoure/KissNetwork.bundle/commit/5dc5fbaabd1035357f4bf8e9f691f286a4965303 and will notify `cfscrape` dev and see what they have to say.  Patch is not a great solution, but works for the moment.

Pull the latest changes from my dev branch, then once the channel runs, navigate to the DevTools and reset the Header Dictionary.  Refer to [Headers Tools](https://github.com/Twoure/KissNetwork.bundle#header-tools) for more info.

If channel fails to load and you are not able to reset the header dict, then stop your Plex Media Server (PMS) and remove the `Header_Dict` file, then start PMS.  If you need more info on `Header_Dict` file location then let me know.  This will force a refresh of the channel's cached headers.

**Comment by Twoure** [comment]
Fixed in `v1.2.3`.  Refer to release info [here](https://forums.plex.tv/discussion/comment/1210133/#Comment_1210133) on update procedure.

**Comment by nvaldes** [comment]
You, sir, are a gentleman and a scholar.  The patch seems to have done the trick, closing!
