### ISSUE TITLE
"This channel is not responding" when selected an episode to watch

### ISSUE THREAD

**Issue by jchallenger** [Twoure/KissNetwork.bundle#22]
Hi There,

I've getting an error after selecting an episode to watch. The KissNetwork Log outputs no errors except that it cannot find a valid Plex token (at which point it assumes thee user is Admin). The System Log does relay an error (see below)

Log File (after clicking episode to watch):

> 2016-07-13 18:04:04,878 (3b6c) :  DEBUG (runtime:717) - Handling request GET /video/kissnetwork
> 2016-07-13 18:04:04,881 (3b6c) :  DEBUG (runtime:814) - Found route matching /video/kissnetwork
> 2016-07-13 18:04:04,881 (3b6c) :  DEBUG (logkit:13) - ********************************************************************************
> 2016-07-13 18:04:04,881 (3b6c) :  DEBUG (logkit:13) - \* Client.Product         = Plex Web
> 2016-07-13 18:04:04,881 (3b6c) :  DEBUG (logkit:13) - \* Client.Platform        = Chrome
> 2016-07-13 18:04:04,881 (3b6c) :  DEBUG (logkit:13) - \* Client.Version         = 2.5.2
> 2016-07-13 18:04:04,882 (3b6c) :  DEBUG (logkit:13) - \* CFTest Previously Passed, not running again.
> 2016-07-13 18:04:04,882 (3b6c) :  DEBUG (logkit:13) - ********************************************************************************
> 2016-07-13 18:04:04,884 (3b6c) :  DEBUG (logkit:13) - \* Checking if user is Admin
> 2016-07-13 18:04:04,884 (3b6c) :  DEBUG (logkit:13) - \* Auth URL   = http://127.0.0.1:32400/myplex/account
> 2016-07-13 18:04:04,884 (3b6c) :  ERROR (logkit:22) - \* NO Plex Token available for validation
> 2016-07-13 18:04:04,884 (3b6c) :  DEBUG (logkit:13) - \* Assuming current user is Admin
> 2016-07-13 18:04:04,884 (3b6c) :  DEBUG (logkit:13) - ********************************************************************************
> 2016-07-13 18:04:04,892 (3b6c) :  INFO (datakit:131) - Saved the dictionary file
> 2016-07-13 18:04:04,901 (3b6c) :  DEBUG (networking:161) - Fetching 'https://api.github.com/repos/Twoure/KissNetwork.bundle/releases/latest' from the HTTP cache
> 2016-07-13 18:04:04,911 (3b6c) :  DEBUG (base:117) - Checking if com.plexapp.plugins.kissnetwork is broken
> 2016-07-13 18:04:04,913 (3b6c) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMzEKY29tLnBsZXhhcHAucGx1Z2lucy5raXNzbmV0d29ya3MxMAppZGVudGlmaWVycjAK'
> 2016-07-13 18:04:04,921 (3b6c) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 2059 bytes

System Log:

> 2016-07-13 18:04:05,187 (119c) :  CRITICAL (core:574) - Exception when calling function 'MetadataObjectForURL' (most recent call last):
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 294, in call_named_function
>     result = f(_args, *_kwargs)
>   File "D:\Users\Admin\AppData\Local\Plex Media Server\Plug-ins\KissNetwork.bundle\Contents\Services\URL\KissVideo\ServiceCode.pys", line 44, in MetadataObjectForURL
>     thumb, art = Metadata.get_thumb_and_art(html, url)
>   File "D:\Users\Admin\AppData\Local\Plex Media Server\Plug-ins\KissNetwork.bundle\Contents\Services\Shared Code\metadata.pys", line 94, in get_thumb_and_art
>     cover_url = Common.CorrectCoverImage(html.xpath('//head/link[@rel="image_src"]/@href')[0])
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
>     _getitem_           = lambda x, y: x.**getitem**(y),
> IndexError: list index out of range
> 
> 2016-07-13 18:04:05,187 (119c) :  CRITICAL (services:745) - Exception calling function in URL service "KissVideo" (com.plexapp.plugins.kissnetwork)
> 2016-07-13 18:04:05,187 (119c) :  CRITICAL (core:574) - Exception (most recent call last):
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request
>     result = f(*_d)
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\handlers\services.py", line 26, in url_lookup
>     c = self._core.services.metadata_object_for_url(url, in_container=True)
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\services.py", line 725, in metadata_object_for_url
>     return self._get_result_from_function_for_url(self.metadata_object_for_url_from_service, url, do_normalization, dict(add_items_automatically = add_items_automatically, allow_deferred = allow_deferred, in_container = in_container))
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\services.py", line 741, in _get_result_from_function_for_url
>     result = func(url, service, *_kwargs)
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\services.py", line 642, in metadata_object_for_url_from_service
>     metadata = self._call_named_function_in_service(METADATA_OBJECT_FUNCTION_NAME, service, [url])
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\services.py", line 589, in _call_named_function_in_service
>     return self._call_named_function_in_sandbox(service.sandbox, fname, None, f_args, f_kwargs, allow_deferred, raise_exceptions, f_optional)
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\services.py", line 573, in _call_named_function_in_sandbox
>     result = sandbox.call_named_function(fname, allow_deferred=allow_deferred, raise_exceptions=raise_exceptions, args=f_args, kwargs=f_kwargs, mod_name=mod_name, optional_kwargs=f_optional)
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 294, in call_named_function
>     result = f(_args, *_kwargs)
>   File "D:\Users\Admin\AppData\Local\Plex Media Server\Plug-ins\KissNetwork.bundle\Contents\Services\URL\KissVideo\ServiceCode.pys", line 44, in MetadataObjectForURL
>     thumb, art = Metadata.get_thumb_and_art(html, url)
>   File "D:\Users\Admin\AppData\Local\Plex Media Server\Plug-ins\KissNetwork.bundle\Contents\Services\Shared Code\metadata.pys", line 94, in get_thumb_and_art
>     cover_url = Common.CorrectCoverImage(html.xpath('//head/link[@rel="image_src"]/@href')[0])
>   File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f46e7e6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
>     _getitem_           = lambda x, y: x.**getitem**(y),
> IndexError: list index out of range
> 
> 2016-07-13 18:04:05,190 (119c) :  DEBUG (runtime:924) - Response: [500] 3433 bytes

**Comment by Twoure** [comment]
Yup, I made a post in the [forums](https://forums.plex.tv/discussion/comment/1217247/#Comment_1217247) about this issue already.  Kissanime changed from `https` to `http` causing this error.  Fixed this about an hour ago, and will push `v1.2.4` out soon (after some more testing).

**Comment by Twoure** [comment]
Fixed in [v1.2.4](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.4)

**Comment by Twoure** [comment]
@jtchallenga does `v1.2.4` fix your issue?

**Comment by rahlquist** [comment]
Twoure,

I have v1.2.4 and while it worked initially it is again now giving this same error. 
[tmp-plexlog.txt](https://github.com/Twoure/KissNetwork.bundle/files/373744/tmp-plexlog.txt)

**Comment by Twoure** [comment]
@rahlquist seems like the service code did not register after installation. To fix, try restarting your Plex Media Server.

**Comment by Twoure** [comment]
@jtchallenga does [v1.2.6](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.6) fix your issue?

**Comment by jchallenger** [comment]
I think it did, been running pretty smoothly since. Thanks!
