### ISSUE TITLE
Video Unavailable

### ISSUE THREAD

**Issue by shutokou** [Twoure/KissNetwork.bundle#23]
I've been having this issue for roughly a week, and been ignoring it because sometimes  Kiss Network simply goes down, only to return later. As always, the video tries twice to load, never reaching past 13%, before giving me the error message of "this video is unavailable". I've installed the latest version, and even completely deleted the Kiss Network folder, closed PMS, loaded the new version, and restarted with no luck.

I have multiple log files, and aren't quite sure as to which you would need.

[complexapppluginskissnetwork.zip](https://github.com/Twoure/KissNetwork.bundle/files/387413/complexapppluginskissnetwork.zip)

**Comment by Twoure** [comment]
The log files your provided are correct.  From them I can see that you are running PMS v0.9.12.4, which I've never tested this channel with. _(Note: first PMS version I tested the original channel with was v0.9.12.12 on 09/19/15)_

Also from the logs:

``` bash
ERROR (logkit:22) - * This Video is broken, KissAnime is working to fix it.
```

But If I check the same video, I can see it does have videos and they are not broken.  This error message logs whenever the code parses the page but cannot find the video source list.

My assumption is the Service code is having issues properly handling the site cookies, returning the cloudflare validation page instead.

Currently I've been re-working how the cookies are handled.  Try my [dev](https://github.com/Twoure/KissNetwork.bundle/tree/dev) branch and see if it solves the issue.  Please provide logs again if it fails, and let me know how it goes.  _([dev zip download link](https://github.com/Twoure/KissNetwork.bundle/archive/7f10ec64d746dfb772fec6daa83f46b248f513a7.zip))_

**Comment by shutokou** [comment]
I've tried using the dev branch download, and the channel never appears in my Plex list. I installed the 1.2.4 prep version, and while that solves the issue of the channel not appearing in the list, the same old problem of videos being unavailable persists.

I sincerely appreciate all of your efforts and any further help.

~~Plex Media Server.zip~~ _(removed logs because `Plex Media Server.log` includes user authentication token.)_

**Comment by Twoure** [comment]
@shutokou, removed your log files because the auth token was logged within the `Plex Media Server.log`  There is a setting for your server that will disable the token within logs.  For future reference Please disable auth token logging before uploading the `Plex Media Server.log`.  Also for this channel I normally do not need the `Plex Media Server.log` file, only the channel log and system log.

**Comment by Twoure** [comment]
@shutokou I suggest you reset your Auth token via the instructions in [Comment_299539](https://forums.plex.tv/discussion/comment/299539/#Comment_299539). If you run into issues, [here](https://support.plex.tv/hc/en-us/articles/204281528-Why-am-I-locked-out-of-Server-after-password-reset-or-device-token-removal-) is some more info to help.

**Comment by shutokou** [comment]
[com.plexapp.plugins.kissnetwork.zip](https://github.com/Twoure/KissNetwork.bundle/files/389647/com.plexapp.plugins.kissnetwork.zip)
Thank you for that Twoure, I was unaware. All tokens have been reset, but do you have any ideas on how to restore playback functionality?

**Comment by Twoure** [comment]
> do you have any ideas on how to restore playback functionality?

So a month ago-or-so cloudflare changed their anti-bot code, and I didn't catch it in time.  This resulted in the channel hammering cloudflare with bad requests resulting with many users being presented with a captcha verification.  Some more info can be found [here](https://forums.plex.tv/discussion/comment/1201031/#Comment_1201031).

Some users have reported seeing the captcha popup on the video page only, others right after the 5 sec page finishes.  These are all in relation to using a web browser from the same IP as their PMS.

Something to try (if possible) is to open a web browser from the same computer that host your PMS and try to watch the same anime as before.  If there is a captcha involved, then this is your issue.  Some users have said that the channel code will work after passing the captcha (on the machine hosting the channel code).

**Comment by shutokou** [comment]
Sorry for the late reply, as it has been a busy weekend here. What you described seems to have worked, and I greatly appreciate it.

You do awesome work, and if you have a donation page let me know, I'd be happy to contribute.
