### ISSUE TITLE
Menu navigation - stuck in show after sleep

### ISSUE THREAD

**Issue by swotai** [Twoure/KissNetwork.bundle#25]
Using the channel on openPHT embedded.  after watching show e.g. on anime channel, sometimes i just left the client alone in the particular show's page, showing all episodes.  The client go to sleep after 30 min of inactivity.  After wake up, the client will revert back to the main screen showing all libraries.  When going back to the kissnetwork channel, it'll be stuck in the show episode page, pressing escape or backspace would go out to the menu for choosing channels.  

is this an issue with the bundle or issue with openPHT?

**Comment by Twoure** [comment]
> is this an issue with the bundle or issue with openPHT?

Sorry, not sure.  Assuming is a limitation of OpenPHT and channels, but very-well could be my channel.

I will be releasing `v1.2.5` sometime next week, so hoping it will fix this issue, but no promises.

**Comment by Twoure** [comment]
Please try [v1.2.7](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.7) and let me know if it fixes this issue.

**Comment by Twoure** [comment]
[v1.2.8](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.8) now available.  If you have further issues after updating to `v1.2.8`, then please refer to [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue).
