### ISSUE TITLE
does not work KissNetwork

### ISSUE THREAD

**Issue by chocolatesuper** [Twoure/KissNetwork.bundle#32]
not stable when will be released an update to fix that 2016 and came out a version but not the stable maintenance delen to work in the plex bundle

**Comment by Twoure** [comment]
Please review [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue), then include the proper log files as an attachment.

**Comment by chocolatesuper** [comment]
@Twoure  actualizar cuando llega una nueva versión en septiembre el año 2016

**Comment by chocolatesuper** [comment]
When upgrade comes a new version in September 2016

**Comment by chocolatesuper** [comment]
@Twoure  When will be upgraded a kissNETwork version?

**Comment by Twoure** [comment]
Current stable version is [v1.2.7](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.7).  I have no timeline for the next version, as it will only include an update for the Openload server code.

If your KissNetwork channel is not working, then please review the [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue) wiki, then include the proper log files as an attachment.

For general help, checkout the Plex forum support thread for this channel [here](https://forums.plex.tv/discussion/186988).

**Comment by Twoure** [comment]
[v1.2.8](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.8) now available.  If you have further issues after updating to `v1.2.8`, then please refer to [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue).
