### ISSUE TITLE
Please wait while channel caches headers message

### ISSUE THREAD

**Issue by ghost** [Twoure/KissNetwork.bundle#35]
I keep getting this message: 

> Please wait while channel caches headers. Exit channel and try again later.

and nothings shows up, I restarted plex several times but still no luck

**Comment by ghost** [comment]
now the message is gone but every time I go to alphabetical folder it says "A list is empty" when I go to latest updates folder it says "list is empty"

**Comment by Twoure** [comment]
Please review [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue), then add the appropriate logs/info to your original post.
