### ISSUE TITLE
"There was a problem playing this item." kisscartoon

### ISSUE THREAD

**Issue by greatwroth** [Twoure/KissNetwork.bundle#37]
Only on kisscartoon videos, I get a message "There was a problem playing this item." on almost every video. http://pastebin.com/Pmt85m6L verbose log started just before testing then copy paste

**Comment by Twoure** [comment]
[v1.2.8](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.8) now available.  Also all the sites were offline during the time of this error.  

Refer to [(KissAnime admin) This is what happen to Kiss sites in the last two weeks](https://www.reddit.com/r/KissAnime/comments/5iy7oy/kissanime_admin_this_is_what_happen_to_kiss_sites/) for more info.

If you have further issues after updating to `v1.2.8`, then please refer to [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue).
