### ISSUE TITLE
Update "kissanime.to" to "kissanime.ru"

### ISSUE THREAD

**Issue by HowellBP** [Twoure/KissNetwork.bundle#39]
It appears that kissanime.to isn't responding to stream requests. I manually changed kissanime.to to kissanime.ru in Services/ServiceInfo.plist and Services/URL/KissVideo/ServicePrefs.json and streaming started working again. Opening kissanime.to just redirects to .ru anyway, but the redirects don't work for streams.

**Comment by Twoure** [comment]
Try changing the [Update Channel](https://github.com/Twoure/KissNetwork.bundle#update-channel) to `Development` as I've done some reworking to the channel and will be releasing `v1.2.8` soon.

As for the domain name change, there is no need to manually change any values, as the channel will auto update the domain names separate from the channel releases.

If you want to force the domain name to update, then [Enable Developer Tools](https://github.com/Twoure/KissNetwork.bundle#enable-developer-tools), and use the [Domain Tools](https://github.com/Twoure/KissNetwork.bundle#domain-tools) by selecting `Update Anime Domain`.  **Domain Tools** are located within the Developer menu in [About / Help](https://github.com/Twoure/KissNetwork.bundle#about--help).

**Comment by Twoure** [comment]
[v1.2.8](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.8) now available.

If you have further issues after updating to `v1.2.8`, then please refer to [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue).
