### ISSUE TITLE
"This directory appears to be empty."

### ISSUE THREAD

**Issue by ThisIsAlanB** [Twoure/KissNetwork.bundle#4]
For both my Nexus 7 (Android Tablet) and my Nexus Player (Android TV), I can't access anything in the library. Both are running the latest version of Android and the latest version of Plex.

[com.plexapp.plugins.kissnetwork.txt](https://github.com/Twoure/KissNetwork.bundle/files/118501/com.plexapp.plugins.kissnetwork.txt)

[com.plexapp.system.txt](https://github.com/Twoure/KissNetwork.bundle/files/118502/com.plexapp.system.txt)

**Comment by Twoure** [comment]
Please try the latest release [v1.0.8](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.0.8) and let me know if it works for you.  Make sure to restart Plex Media Server after update for the service code to be implemented properly.

**Comment by ThisIsAlanB** [comment]
Just updated and restarted PMS (even updated it to the latest version of PMS). I'm still having the same issue unfortunately.

**Comment by Twoure** [comment]
Please post new logs after update.

**Comment by ThisIsAlanB** [comment]
[com.plexapp.plugins.kissnetwork.txt](https://github.com/Twoure/KissNetwork.bundle/files/120460/com.plexapp.plugins.kissnetwork.txt)
[com.plexapp.system.txt](https://github.com/Twoure/KissNetwork.bundle/files/120461/com.plexapp.system.txt)

**Comment by Twoure** [comment]
Does this file exist?
`C:\Users\Alan\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.plugins.kissnetwork\Header_Dict`

If not then most likely it is a permissions error.  Try using the developer tools to manually updated headers.

**Comment by ThisIsAlanB** [comment]
~~How would I go about doing that?~~

Nevermind

**Comment by Twoure** [comment]
@ThisIsAlanB get it working?

**Comment by ThisIsAlanB** [comment]
Nope. Ended up not figuring out what you were talking about with dev tools and how to fix headers. All I tried was taking ownership of the entire Plex folder in AppData and that didn't seem to work.

**Comment by Twoure** [comment]
Here is info about [developer tools](https://github.com/Twoure/KissNetwork.bundle#enable-developer-tools).  Refer to the [Header Tools](https://github.com/Twoure/KissNetwork.bundle#header-tools) section for manually resetting headers.

As I asked in [comment-180872732](https://github.com/Twoure/KissNetwork.bundle/issues/4#issuecomment-180872732) does the header_dict file exist?  If not it would seem Plex is having issues writing to that directory.

**Comment by ThisIsAlanB** [comment]
It does not. And I checked there. I don't know where to go from there. I'm no developer.

**Comment by Twoure** [comment]
Is the channel installed in the correct plug-ins folder?
https://support.plex.tv/hc/en-us/articles/201106098-How-do-I-find-the-Plug-Ins-folder-
some people install channels within the system Plug-ins folder by accident (which is incorrect).  The system Plug-ins folder will look like `Plug-ins-<hash>` where the `<hash>` is a combo of numbers and letters.

**Comment by ThisIsAlanB** [comment]
It's installed to the right folder

![plex plugins](https://cloud.githubusercontent.com/assets/13711807/13096310/81a3e228-d4e6-11e5-8b89-3c15b265077f.png)

**Comment by ThisIsAlanB** [comment]
Now I'm able to see everything in the directories (I reinstalled it manually. Originally I was using the unsupported app store). Now I'm having some other issues. A. I can't play videos at all (getting an error that tells me to restart both the app and server, even after following those steps). And B. I can't see everything when going through the alphabetical folders (like when going through B on the cartoon page, there's a cutoff point so I can't find shows like Bojack Horseman).

[com.plexapp.plugins.kissnetwork.txt](https://github.com/Twoure/KissNetwork.bundle/files/133536/com.plexapp.plugins.kissnetwork.txt)
[com.plexapp.system.txt](https://github.com/Twoure/KissNetwork.bundle/files/133537/com.plexapp.system.txt)

**Comment by Twoure** [comment]
Follow the steps outlined in issue https://github.com/Twoure/KissNetwork.bundle/issues/6 to fix the Plex Token Issue.  I'll spend time later this week fixing the Plex Token issue.

Let me know how it goes.

**Comment by ThisIsAlanB** [comment]
Should I find the token in my own library, or use the Kiss plugin's? I'm not seeing the token using my own media. And the string using Kiss changes depending on which file I choose.

**Comment by Twoure** [comment]
You're saying the `X-Plex-Token=` part changes? The URL will differ depending on what file you're accessing, but the token part should be the same.

**Comment by ThisIsAlanB** [comment]
I'm not even seeing where it says `X-Plex-Token=` no matter what movie or show I choose in my own library.

**Comment by Twoure** [comment]
Just to clarify, you don't see a plex token within the url when selecting the _view xml_ for personal or channel media?  Will look like this (replaced my plex token with x's and removed ip for confidentiality)

![screenshot 1455735903_edit](https://cloud.githubusercontent.com/assets/13565327/13121503/22eeef6a-d578-11e5-8cb8-2286ba13c036.png)

**Comment by ThisIsAlanB** [comment]
Sorry for making things difficult. I didn't see it when I logged into Plex through the IP. Logged in through plex.tv and it worked. Everything appears to be working now. I'm still having issues going to the next page on both my Android Tablet and Android TV (I see it just fine in browser on PC). I wouldn't know if that's Plex's fault, or something else. Thank you very much!

**Comment by Twoure** [comment]
Android should auto load the next page, making one long continuous directory.  Scroll to the bottom, wait a second or two (depends on your computer and bandwidth) then try to scroll down again.  The next page should appear.

**Comment by Twoure** [comment]
Closing issue since you issue was resolved.  Please open another issue if you have one.
