### ISSUE TITLE
search functionality

### ISSUE THREAD

**Issue by danielb2** [Twoure/KissNetwork.bundle#43]
there's a lot of content. Would be nice if I could search content. For instance, I wanted to watch `ReLife` repisode 3 again, and I had to select alphabets, R, and then wade through several pages.

Would have loved to be able to just search for `ReLife` somewhere

**Comment by Twoure** [comment]
Search Function is already included.  Plex Web client does have some issues, https://forums.plex.tv/discussion/comment/1175175/#Comment_1175175.

Note: not all Plex Clients support channel searching, refer to https://forums.plex.tv/discussion/comment/1226086/#Comment_1226086 for more info.
