### ISSUE TITLE
v1.2.8 on xbox360

### ISSUE THREAD

**Issue by j00j4nt200** [Twoure/KissNetwork.bundle#46]
1.2.8 Doesn't work on xbox360, it can't read directories/anything?
On local pc everything work.
1.2.7 works ok.

**Comment by Twoure** [comment]
Please review [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue), then add the appropriate logs/info to your original post.

**Comment by j00j4nt200** [comment]
I tried clean install in order to correct my post with appropirate logs/info, but now is working :)
I'm sorry for false issue.
Jovan
