### ISSUE TITLE
Cannot play anything

### ISSUE THREAD

**Issue by ghost** [Twoure/KissNetwork.bundle#48]
This started last night, every video I tried to watch through the Kiss channel kept saying "There was a problem playing this item." I left it alone till this morning. I have switched it to Openload and switched into Development mode. I saw a button that said to click it to update something, when I clicked it, was told that it couldn't update. Now I cannot get the update button to come back, nor can I watch anything on the Kiss channels. 
 My movies and other things work fine. Watching stuff on other channels works too. Its only Kiss thats doing it.

**Comment by cerinthus** [comment]
Can confirm that switching to development has no effect.

**Comment by Twoure** [comment]
Refer to https://github.com/Twoure/KissNetwork.bundle/issues/47#issuecomment-275310287 and https://github.com/Twoure/KissNetwork.bundle/issues/47#issuecomment-275547142 for more info.

**Comment by cerinthus** [comment]
Installing dev branch manually still produces failures on openload links for me. 

The update in the channel doesn't appear for me. Switching to dev branch had no effect whatsoever.

**Comment by mchawi** [comment]
Strange... It worked for me. This may sound like a stupid question but, did you take the folder out of the zip file? Also did you delete the -dev in the file name? Have you tried restarting pms? (ps: i didnt see the update also i had to do it manually)

**Comment by cerinthus** [comment]
Odd.  No zip, just cloned the dev branch and moved the folder (nothing to rename either). No dice.

**Comment by mchawi** [comment]
Sorry i apologize if i am saying stupid things,  but where did you get the file, in the issue #47? also what is the name of the thing you are putting in the pms pluggins folder? because mine is KissNetwork.bundle

I got it from a zip file that was linked in issue #47 that is linked to the word "download". I opened up the zip and the pms puggins folder and through in the folder that was inside the .zip

and i right clicked the folder and renamed it to KissNetwork.bundle (It was Kissnetwork.bundle-dev) Then I restarted pms and it worked.. hope im helping, i dont know much about plex so, im just going off of what i just figured out

**Comment by cerinthus** [comment]
git clone, git checkout dev, git pull. 

Should be identical to the released zip.

**Comment by mchawi** [comment]
nvm... :( it seems like the only thing that works is one piece episode 541 sub... Why? idk... :(

**Comment by Twoure** [comment]
> @cerinthus said:
> git clone, git checkout dev, git pull.
>
> Should be identical to the released zip.

Correct, but remember to restart PMS, otherwise the changes within the service code will not take effect.

**Comment by Twoure** [comment]
@Kihluna  and @cerinthus 

Please review [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue), then add the appropriate logs/info to your original post.

**Comment by cerinthus** [comment]
Done.

I think I've solved the problem though.  Manually editing the settings to change the server value to 2 resolves the problem.

Similarly, manually editing the update channel to 2 allows the dev update button to appear, so you don't have to do it manually from the stable branch.  For some reason it's not writing settings properly.

I'd say permissions are the obvious problem and entirely my fault, except it reproduces on Windows

**Comment by Twoure** [comment]
> @cerinthus said:
> Now it's working fine, with all servers. I have no idea why, I've changed nothing, but you could close the issue.

I would, but you didn't start the issue, sorry. 

@Kihluna is your issue resolved?

**Comment by ghost** [comment]
actually yeah. I just tried it and its working fine. odd
