### ISSUE TITLE
Plex Media Server is not responding

### ISSUE THREAD

**Issue by Yolley** [Twoure/KissNetwork.bundle#49]
I am using latest plex media server on my vps (Ubuntu 16.04). Today first time installed kissnetwork, restarted pms and vps several time, but every time i try to watch something, i get one of the two errors:
Channel is not responding (in browser only)
Plex Media Server is not responding (in plex media player and browser sometimes).

Here are my logs.
[kissnetwork.log.zip](https://github.com/Twoure/KissNetwork.bundle/files/790491/kissnetwork.log.zip)

**Comment by Yolley** [comment]
The problem appears only with kissnetwork, i can watch everything from my library.

**Comment by Twoure** [comment]
Without seeing your `com.plexapp.system.log` from the same time, I cannot be sure, but I can see you've enabled `Force Transcoding`.  For myself (on Ubuntu 14.04) the last public PMS version to handle channel transcoding correctly is 1.3.0.  As of today, PlexPass PMS v1.4.2 has fixed the channel transcoding issue.

So, try un-checking the `Force Trancode` preference.  If error still persist, then please review [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue), then add the appropriate logs/info to your original post.

**Comment by Yolley** [comment]
Thank you for answer!
Error first time appeared without Force Transcode, i enabled this option later to test. I decided just to reinstall pms, and now it works fine.
