### ISSUE TITLE
Channel not appearing

### ISSUE THREAD

**Issue by godsplague** [Twoure/KissNetwork.bundle#5]
Hello, pretty novice linux user and would really like to see this working but haven't seen anyone else having the same issue as me so I'm not sure whats going on. 

First I tried installing kissnetwork using the Webtools v2 and restarted plex but nothing shows up under the channel. So I uninstalled it from webtools and manually installed it, but it still never appears under the channels. The file pathing seems correct, in the Plug-ins/KissNetwork.bundle/Contents format. I checked the file permission and they're set as the same as the other channels that seems to work. I have other channels that appear from the plex web browser correctly. Any advice would be appreciated.

I thought I might've been a java issue but attempting to install python tells me python is already the newest version. I attached the log for plugins here as well

[com.plexapp.plugins.kissnetwork.txt](https://github.com/Twoure/KissNetwork.bundle/files/125819/com.plexapp.plugins.kissnetwork.txt)

**Comment by Twoure** [comment]
From you logs
`RuntimeUnavailable: Could not find a JavaScript runtime.`

This channel requires a JavaScript runtime.  Refer to [Channel Support](https://github.com/Twoure/KissNetwork.bundle#channel-support) for java install.  Install java and then restart PMS for channel to work.

**Comment by godsplague** [comment]
Sorry for inexperience, doesnt openjdk have java runtime? On debian running apt-get install openjdk-7-jre but its already the newest version. Running apt-get install nodejs returns an unable to locate package error. Thanks for such a fast response
Running java -version tells me
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Comment by Twoure** [comment]
This channel uses [PyExecJS](https://github.com/doloopwhile/PyExecJS). Valid javascript runtimes are listed [here](https://github.com/doloopwhile/PyExecJS#details).  I suggest pushing forward with installing node.js.

Here is the [documentation](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) for installing node.js on debian/ubuntu.

**Comment by godsplague** [comment]
Thank you, took a little working but got node.js to install, I hadn't seen instructions using the curl method yet and that seemed to be my solution. I restarted plex and now the channel seems to be working.
Thanks again for what was probably basics to you heh

**Comment by Twoure** [comment]
Glad to hear it's working.
FYI I also support this channel in the Plex forums https://forums.plex.tv/discussion/186988.  Sometimes other users have written in on issues and I answer them there, but you can always create an issue here.

Closing issue now.
