### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by Baeghab** [Twoure/KissNetwork.bundle#52]
I have the KissAsian addon for Kodi on my FireStick and for a week it's been working fine but yesterday it prompted for captcha, asking whether or not I was human. 

The developers of the latest patch and updates said the problem could be solved by going in browser and completing the captcha. But I've been using KissAsian for nearly a year now and have never been prompted to complete a captcha. 

I tried for 6 hours last night, using three different accounts, three different devices, and three different browsers and could not get the captcha to prompt outside Kodi so I have no way to get rid of the captcha in Kodi.

The cookies are enabled. I always clear the cache before I try logging in again. I logged in on the addon in Kodi. I tried book marking the show I was watching, etc. I can't get rid of the captcha notice in Kodi.

**Comment by Twoure** [comment]
Sorry, but this is a Plex channel NOT Kodi related.
