### ISSUE TITLE
There was a problem playing this item

### ISSUE THREAD

**Issue by SiddhantArya** [Twoure/KissNetwork.bundle#54]
I have been getting "There was a problem playing this item" error when I'm trying to play certain titles like One Piece (currently added to Bookmarks). I was able to play these videos up till 3 days ago, but haven't been able to run it since. 
I have tried all the Plex workarounds mentioned in the online forums like 
- Optimising the database
- Updating my Plex Library
- Setting a different temporary directory for Transcoding 
- Disabling Old Devices on the General Settings for Plex
and the like. 

I have tried to play the videos on Chrome(Web), Safari(Web) and on Samsung Smart TV Plex App with no luck.

Error Screen: 
<img width="1636" alt="screen shot 2017-03-16 at 4 39 49 pm" src="https://cloud.githubusercontent.com/assets/4563515/23993632/5bec0454-0a67-11e7-98ed-7ed973fecfdf.png">

**Comment by Twoure** [comment]
Duplicate issue of https://github.com/Twoure/KissNetwork.bundle/issues/53
