### ISSUE TITLE
Video not found 

### ISSUE THREAD

**Issue by kasskid** [Twoure/KissNetwork.bundle#55]
add a search  bar

**Comment by kasskid** [comment]
comics and manga work fine anime,cartoon and drama do not the y work some on version 1.2.7

**Comment by Twoure** [comment]
> add a search bar

Refer to https://github.com/Twoure/KissNetwork.bundle/issues/43#issuecomment-272327802

> comics and manga work fine anime,cartoon and drama do not the y work some on version 1.2.7

Duplicate issue of https://github.com/Twoure/KissNetwork.bundle/issues/53
