### ISSUE TITLE
There was a problem playing this item.

### ISSUE THREAD

**Issue by cobaltsteele** [Twoure/KissNetwork.bundle#56]
I'm getting this error message on all Anime as of late, I've recently updated my Plex server as well as replaced my KissNetwork.bundle with your newest version.

This is the case on all of my devices. Curious as to if anyone knows a fix or if this is a known issue?

I live off this bundle so thank you! But I'd love to get it going again.

**Comment by cobaltsteele** [comment]
[logs.zip](https://github.com/Twoure/KissNetwork.bundle/files/849773/logs.zip)

Running on PC and PS4 with same issue
Plex Version 3.1.1
KissNetwork Version 1.2.9

**Comment by Twoure** [comment]
Duplicate issue of https://github.com/Twoure/KissNetwork.bundle/issues/53
