### ISSUE TITLE
"Video Unavailable Sorry, but we can't play this video. OR Can't play this item"

### ISSUE THREAD

**Issue by IJ08** [Twoure/KissNetwork.bundle#58]
**KissNetwork (version)** - 1.2.9
**Plex Media Server (version)** - Latest (Just downloaded 2 days ago), sorry can't check it now, will update post later
**Operating System** - Windows 10
**Plex Client (if applicable)** - Plex channel running on ROKU TV

**Description**:

Installed PMS latest on Windows 10. Installed Kissnetwork bundle 1.2.9 on plug-ins. Installed PLEX channel on ROKU TV. Able to view MANGA using Kissnetwork. Able to see titles and search Anime, Cartoons alphabetical with thumbnails. So the kissnetwork plug-in is definitely working in regards to querying from the original sites. Both PMS and ROKU TV are on same network.

Issue: 

On ROKU TV, playing an anime video, any type of anime title or cartoon title will end up showing green screen, a progress count 13%-15% (I guess this is normal) and then stops with an error message "Video Unavailable Sorry, but we can't play this video. The original video may no longer be available....".  There are also some instances wherein it will show error "Can't play this item"

So I tried doing it directly on my PMS, checking the channel, logging into it and playing ANIME series titles and ending up with same error - "Sorry. Can't play this item"

I have tried several times power cycling ROKU and my PMS but the issue remains. Anime and cartoon are getting this error (Did not check DRAMA), Manga works fine.

**Log Files** - I will update the log files later when I get home. Currently away and did not turn on public login to my server. I would hope the description would tell you or make you folks remember something immediately. If not, I will update logs around 6pm ET.

**Comment by bearsnacks** [comment]
I'm having the exact same issue

**Comment by Twoure** [comment]
Duplicate issue of https://github.com/Twoure/KissNetwork.bundle/issues/53
