### ISSUE TITLE
Could You Write Those For Me in Highways99 Forum in Addons.Center ??? Registrations are Closed.

### ISSUE THREAD

**Issue by ISSUES999** [Twoure/KissNetwork.bundle#60]
i have been monitoring the kissanime site and i noticed that they put a second fduid in kissanime server video pages for subbed and removed cf clearance for openload video pages at first then added the second cfduid on the main page and now on the dubbed videos too , and removed asp-net from main page only so far.
the cookie file of Highways kissanime addon doesnt get updates for asp-net if you have one from an older version of the addon than can be keeped and if you remove the cookie file and then enter the addon and from there an anime u will get a full cookie but without the set cookie-3=asp.net , i tried adding manually a second fduid entrie but after you enter the addon and an anime or click on an episode if it happens there , the second fduid entrie disappears from the cookie file.
the kissanime.to entries from older versions of the addon are not getting updated either and dont exist in the new cookie .
the updates 0.9.20 and 0.9.21 apparently are not from highway99 but from tv addons repo kissanime plugin by "gaining".
Thanks in Advance - Have a Nice Day Twoure , Bye.

**Comment by Twoure** [comment]
http://forums.addons.center/register/

Hmm, weird.

Sorry, I don't maintain the kodi repo.
@Prometheusx-git is the current user helping to patch @HIGHWAY99's kiss channels.
