### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by ISSUES999** [Twoure/KissNetwork.bundle#61]
could you let prometheusx know (highways addons.center forum)that the links dont show today , they did yesterday (3b.mp4) , also he should remove fav4 image-updater cause some times it causes the favorites not to open when they have anime inside and also sometimes after you press fav4 image-updater to cause kodi to hang indifinetely when you try to exit "kodi" (error: appHangb1).
if i recall correctly gaining pushed out  an old version of his when highway didnt had time long time ago to fix the addon unsuccesfully and the fav4 anime updater was there causing  some kodi crashes and favorites problems reported.
refresh of the main page is slower than the previous versions , the 3b.mp4 links i think (not sure) they were appearing in an old version of highways maybe late 2014.
some interference will occur from gainings 0.9.23 version if you install once and if you delete it and try to install 0.9.19 from highways repo when you get to the addon it will say 0.9.23 , if you install from your desktop then addon will display the correct number but as soon as u enter the "install updates" in the ad ons browser the update will disappear and the addon will change to 0.9.23 , the solution to avoid this is to unistall tv addons repo and not just disable it.
can you also inform z89x23 in highways99 forum (addons.center)that im from the same region europe and since the addon worked for me yesterday it should work for him , provided we will need a new decryption key again.
thanks Twoure and prometheusx , have a very nice day.!!!

(a bit of an update : it appears that they switched the servers for the new episodes to openload and beta server i dont know if the addon works cause im using the site for know , prometheusx any chance we can get beta server instead of stream in the addon ? openload kinda sucks in graphics and speed)bye.!!

**Comment by Twoure** [comment]
Sorry, I don't maintain the kodi repo.
@Prometheusx-git is the current user helping to patch @HIGHWAY99's kiss channels.
