### ISSUE TITLE
There was a problem playing this item.

### ISSUE THREAD

**Issue by itsKastel** [Twoure/KissNetwork.bundle#64]
This issue applies for all of the kissnetwork sites I have tried to access using this site.

**Comment by Twoure** [comment]
Please review [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue), then add the appropriate logs/info to your original post.

**Comment by itsKastel** [comment]
KissNetwork version: 1.2.9
Plex Media Server version: 3.2.1
Operating System: Windows 10 Home Edition
Plex Client: Using browser (Browser is Vivaldi). Does not work on phone either, running Android 7.1.1.
Description: The title lel 😛 
Log Files: Attached items

Edit: Github won't allow me to upload my zip file containing the logs. Instead I uploaded them to G Drive, hope you will still take them. Here's the link. https://drive.google.com/open?id=0B4tfkFl9cvxGTTBhWU1wOGNreFE

**Comment by Twoure** [comment]
Seems something in the decryption isn't working for your variant of the code.  Please try https://github.com/Twoure/KissNetwork.bundle/issues/63 and upload/link your zip file to that issue thread.

**Comment by itsKastel** [comment]
Fixed the issue in the end. At the time of opening this issue, none of the servers had been working. But now I changed to OpenLoad to see if it would work for the last time, and it did. Thanks for making this plugin 👍

**Comment by ghost** [comment]
@KastelOfficial @Twoure isn't kisscartoon down? how are you able to play videos?

**Comment by Twoure** [comment]
@LittleHamster, channel uses kimcartoon _(currently in `dev` branch)_, read [Official Kiss-Affiliated Sites & Status](http://forum.kissanime.com/index.php?threads/updated-05-03-17-official-kiss-affiliated-sites-status.1453/#post-14320) for more info.

**Comment by LittleHamster** [comment]
@KastelOfficial oh okay, I just downloaded the dev branch and tested and I got this error `This channel is not responding.` is this a known issue? thanks
