### ISSUE TITLE
kisscartoons.se is now kimcartoon.me

### ISSUE THREAD

**Issue by MrDemocracy** [Twoure/KissNetwork.bundle#69]
Kisscartoons.se is now kimcartoon.me, could this please be implemented?

**Comment by Twoure** [comment]
Already is implemented in the `dev` channel.
Follow steps 1 - 3 in https://github.com/Twoure/KissNetwork.bundle/issues/63#issue-220801586 for cartoon upgrade.

Do note, even the `dev` channel has some issues currently that need to be resolved.
