### ISSUE TITLE
KissCartoon and KissAsian Video URL Encryption

### ISSUE THREAD

**Issue by Twoure** [Twoure/KissNetwork.bundle#9]
Video links in both KissCartoon and KissAsian are no longer purely base64 encoded.  They now use a custom encoding for the onsite video URLs.
- Cartoon: http://kisscartoon.me/Scripts/kissenc.min.js
- Asian: http://kissasian.com/Scripts/kissenc.min.js

So far KissAnime is unaffected, but I assume it too will follow.

**Comment by Twoure** [comment]
**Update** _(04/24/2016)_

Just finished successfully recreating the JS code to decrypt the new video URLs.  Now to convert it to Python 2.7 and then implement into this channel.

Not as easy as it sounds, from what I read, but the first hurdle is over.  I probably will not work on this much this week, sorry.

**Comment by Twoure** [comment]
**Update** _(04/25/2016)_

Ok, so couldn't leave this alone... it was really bugging me, so just finished translating JS code into Python.  I can once again return the video URLs.  This week is busy so no promises that the fix will be out this week.

**Comment by peakhp** [comment]
is it possible to translate this js code to php

**Comment by Twoure** [comment]
> is it possible to translate this js code to php

Most likely, but I'm not familiar enough with PHP to do so.

**Comment by Twoure** [comment]
Kissasian just came out with a version 2 of their `kissenc.min.js` but Kisscartoon is still the same.
I'll take time later to look into the v2, but so far it doesn't look much different from the original.

**Comment by Twoure** [comment]
> Kissasian just came out with a version 2 of their `kissenc.min.js`

Finished decoding new kissasian v2 js code, and converted to python.

**Comment by Twoure** [comment]
Ran into a roadblock.  Using [PyCrypto](https://github.com/dlitz/pycrypto) v2.6.1, but not able to easily include it into the channels shared libraries.  Instead will have to do something similar to the Trakt [Libraries](https://github.com/trakt/Plex-Trakt-Scrobbler/tree/master/Trakttv.bundle/Contents/Libraries).  This will take me some time to figure out, sorry.

**Comment by Twoure** [comment]
Just realized I can look into pure python alternative to do what I need, which would be easier to implement in this channel.  Will look into later, but wanted to give a glimmer of hope for others.

**Comment by Twoure** [comment]
Finished implementing Plex Framework _friendly_ python decryption code.  Need to do some more testing but currently I can watch googlevideo links from kissasian and kisscartoon again.

**Comment by Twoure** [comment]
Fixed in [v1.1.8](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.1.8)

**Comment by peakhp** [comment]
Thanks for your script, i able to translate it in php

**Comment by Twoure** [comment]
> Thanks for your script, i able to translate it in php

Glad to help.

**Comment by peakhp** [comment]
there is a new changes again with kissasian kissenc.min.js

**Comment by Twoure** [comment]
Thanks, I'll look into this later.

**Comment by Twoure** [comment]
Without digging much, I can see that the AES key is pulled from a POST request that is sha256 encoded.

**Comment by Twoure** [comment]
Ok, so for Kissasian they set an extra cookie the first time a video is played, that cookie acts as a token in the POST headers which later translates into the AES key.  The token seems to stay the same throughout the session until the pass cookie expires.

Currently I don't have time until the weekend to patch this, but know what to do now.

**Comment by Twoure** [comment]
Fixed in `dev` branch.  Testing with different clients right now, but will release `v1.2.0` today to tomorrow with the fix.

Cheers.

**Comment by Twoure** [comment]
Fixed in [v1.2.0](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.0)
